[project]
name = "resource-pack-server"
version = "0.1.0"
description = "A python based Minecraft resource pack server."
readme = "README.md"
license = { text = "GPL-3.0" }
authors = [
    { name = "Mooling0602", email = "clemooling@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mcdreforged>=2.0.0",
]

[dependency-groups]
docs = [
    "sphinx>=6.2.1",
    "sphinx-rtd-theme>=3.0.0",
    "sphinx-autobuild",
    "sphinx-copybutton",
    "sphinx-intl",
    "sphinx-autodoc-typehints",
    "sphinx-prompt",
    "sphinxcontrib-mermaid",
    "sphinx-inline-tabs",
    "sphinx-design",
    "sphinxcontrib-jquery",
]

[project.scripts]
resource-pack-server = "resource_pack_server.__main__:main"
rps = "resource_pack_server.__main__:main"
